
export const PERMISOS_DE_OPERACION = [
    "RTN",
    "DNI",
    "ESCRITURA DE COMERCIANTE INDIVIDUAL",
    "SOLVENCIA MUNICIPAL",
    "COPIA DEL PAGO DE RECIBO DE BIENES INMUEBLES"
  ];
  
  export const SOLICITUD_DE_SOLVENCIA_MUNICIPAL = [
    "DNI",
    "PRESENTARSE PERSONALMENTE"
  ];
  
  export const PERMISOS_PARA_ROTULOS_PUBLICITARIOS = [
    "DNI",
    "RTN DE LA EMPRESA",
    "SOLICITUD PARA LA INSPECCIÓN DEL ROTULO",
    "MEDIDAS DEL ROTULO"
  ];
  
  export const SERVICIO_DE_TREN_DE_ASEO = [
    "SOLICITAR EL SERVICIO EN LA OFICINA DE ADMINISTRACIÓN TRIBUTARIA",
    "REALIZAR LOS PAGOS MENSUALES DEL SERVICIO",
    "DNI"
  ];
  