/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OnNHiDI9hnI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="w-full max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-20 lg:py-24">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 lg:gap-16">
        <div className="space-y-6">
          <div>
            <h2 className="text-3xl md:text-4xl font-bold">Ponte en Contacto</h2>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              ¿Tienes una pregunta o quieres trabajar juntos? Completa el formulario a continuación o contáctanos
              directamente.
            </p>
          </div>
          <form className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label htmlFor="name">Nombre</Label>
                <Input id="name" placeholder="Ingresa tu nombre" />
              </div>
              <div>
                <Label htmlFor="email">Correo Electrónico</Label>
                <Input id="email" placeholder="Ingresa tu correo electrónico" type="email" />
              </div>
            </div>
            <div>
              <Label htmlFor="subject">Asunto</Label>
              <Input id="subject" placeholder="Ingresa el asunto" />
            </div>
            <div>
              <Label htmlFor="message">Mensaje</Label>
              <Textarea className="min-h-[150px]" id="message" placeholder="Ingresa tu mensaje" />
            </div>
            <Button type="submit">Enviar Mensaje</Button>
          </form>
        </div>
        <div className="space-y-6">
          <div>
            <h2 className="text-3xl md:text-4xl font-bold">Información de Contacto</h2>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Encuéntranos en la oficina o ponte en contacto a través de otros canales.
            </p>
          </div>
          <div className="space-y-4">
            <div>
              <h3 className="font-semibold">Dirección</h3>
              <p className="text-gray-500 dark:text-gray-400">Calle Principal 123, Cualquier Ciudad USA 12345</p>
            </div>
            <div>
              <h3 className="font-semibold">Teléfono</h3>
              <p className="text-gray-500 dark:text-gray-400">(123) 456-7890</p>
            </div>
            <div>
              <h3 className="font-semibold">Correo Electrónico</h3>
              <p className="text-gray-500 dark:text-gray-400">info@example.com</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
