
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NavBar } from "@/components/Navbar";
import { Fotter } from "@/components/Fotter";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="light">
      <body className={inter.className}>
      <NavBar/>
        <Providers>{children}</Providers>
        <br />
        <Fotter/>
      </body>
    </html>
  );
}
